# Build Stage
FROM node:<%= nodeVersion %>-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production Stage
FROM nginx:stable-alpine AS production
COPY --from=build /app/<%= outputDir %> /usr/share/nginx/html

EXPOSE <%= PORT %>
CMD ["nginx", "-g", "daemon off;"]
