# Angular SSR Dockerfile
FROM node:<%= nodeVersion %>-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:<%= nodeVersion %>-alpine
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/<%= outputDir %>/browser ./browser
COPY --from=builder /app/<%= outputDir %>/server ./server
RUN npm install --production
ENV PORT=<%= PORT %>
EXPOSE <%= PORT %>
CMD ["node", "server/<%=entryFile%>"]