# Build Stage
FROM node:<%= nodeVersion %>-alpine AS build
WORKDIR /app

COPY package*.json ./
#RUN npm install
RUN <%= installCommand %>

COPY . .

RUN npm install -g @angular/cli
#RUN npm run build
RUN <%= buildCommand %>

# Production Stage
FROM nginx:stable-alpine AS production
COPY --from=build /app/<%= outputDirectory %>/browser /usr/share/nginx/html

EXPOSE <%= PORT %>
CMD ["nginx", "-g", "daemon off;"]
