# Build Sta
FROM node:<%= nodeVersion %>-alpine 
WORKDIR /app

COPY package*.json ./
#RUN npm install
RUN <%= installCommand %>

COPY . .
#RUN npm run build
RUN <%= buildCommand %>
ENV PORT=<%= PORT %>
#CMD ["npm", "run", "start:prod"]
CMD ["<%= runCommand %>", "<%= outputDirectory %>/main"]
